// This file has been autogenerated from a class added in the UI designer.

using System;	
using Foundation;
using AppKit;

namespace ProphetRev4PatchManager
{
	/// <summary>
    /// 
    /// </summary>
	public partial class WindowController : NSWindowController
	{
		/// <summary>
        /// 
        /// </summary>
        /// <param name="handle"></param>
		public WindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
